### PR TITLE
Fix tagline

### PR DESCRIPTION
**Pull request by mnicpt**
Tagline is currently not displaying.

### CODE REVIEW

**Review by gregjopa — APPROVED** [review]
Awesome work @mnicpt! 💯 

I was able to verify this by running smart-payment-buttons locally and adding an alias to paypal-checkout-components pointing to this branch. Looks good!

Screen Shot 2021-01-12 at 4 28 17 PM

The toggle shows and hides as expected using the style.tagline query param.

**Comment by gregjopa** [comment]
The `npm run jest-screenshot` command is currently causing CI to fail. I think we need to regenerate the screenshots. @bluepnume what command can we run to generate new screenshots?

Best I can tell, this commit broke the tag lines and updated the screenshots: https://github.com/paypal/paypal-checkout-components/commit/6f4e280908676fca5313b5b89bcda745688e4581?short_path=80852da#diff-80852da017938de29aee5c4f202d0d3ed8b97345154af7d07308657a4316cf65

Screen Shot 2021-01-12 at 4 47 29 PM

**Comment by mnicpt** [comment]
@gregjopa I think `npm test` will do it.  Checking...

**Comment by mnicpt** [comment]
@gregjopa Looks like I need to add `--updateSnapshot` flag when running tests.

**Review by bluepnume — APPROVED** [review]

**Pull request merged**
