### PR TITLE
Disable trustly

### PR DESCRIPTION
**Pull request by JianyiGao**
Disable Trustly on smart payment buttons

Screen Shot 2021-07-15 at 2 51 29 PM

### CODE REVIEW

**Comment by JianyiGao** [comment]
Not sure why tests failed in the check , ran on local all tests passed
Screen Shot 2021-07-19 at 2 57 39 PM
Screen Shot 2021-07-19 at 2 56 39 PM

**Comment by mnicpt** [comment]
@JianyiGao It will tell you in the build results. Let me know if you need any help.

**Comment by nbierdeman** [comment]
@JianyiGao @mnicpt, it looks like something in the latest release of post-robot is causing the CI to fail. Locally, I pinned post-robot to version `10.0.43`, and now all of the karma tests pass.

**Review by bluepnume — APPROVED** [review]

**Comment by bluepnume** [comment]
Can you rebase against master please?

**Pull request merged**
