### PR TITLE
Add satispay

### PR DESCRIPTION
**Pull request by JianyiGao**
### Description
Enable alipay and satispay for js sdk
https://engineering.paypalcorp.com/jira/browse/DTALTPAY-1115

### Reproduction Steps (if applicable)
Screen Shot 2022-11-06 at 10 05 15 PM

### Dependent Changes (if applicable)
https://github.com/paypal/paypal-sdk-constants/pull/104
https://github.com/paypal/paypal-funding-components/pull/41
https://github.com/paypal/paypal-common-components/pull/60

### Groups who should review (if applicable)

❤️  Thank you!

### CODE REVIEW

**Review by ericyupaypal — CHANGES_REQUESTED** [review]
The *-old.png files in test/screenshot/images/ should not be checked in. Those are indicators of which pngs need to be updated

**Review by wsbrunson — COMMENTED** [review]
Is this okay? otherwise looks good

Image 2022-11-07 at 14 53 59

**Comment by JianyiGao** [comment]
> Is this okay? otherwise looks good
> 
> Image 2022-11-07 at 14 53 59

Per product requirement we do not want to show PayU and Satispay for the vertical stack, so I changed this config `automatic` for PayU https://github.com/paypal/paypal-checkout-components/pull/2020/files#diff-70d312bab5e79e433fe00e85ef9dc3d86f0690d6eabb8a6481d99c45388f4462R15
Therefore screenshots no longer show PayU in vertical stack. Here is a similar change we did in the past 
https://github.com/paypal/paypal-checkout-components/pull/1921/files

**Review by wsbrunson — APPROVED** [review]

**Comment by gregjopa** [comment]
@JianyiGao please remove the dist changes for this PR

**Comment by JianyiGao** [comment]
@gregjopa i have reset the dist file, does this change look okay now?

**Review by gregjopa — APPROVED** [review]

**Pull request merged**
