### PR TITLE
Remove Trustly, PayU Finnish banking from checkout.js 

### PR DESCRIPTION
**Pull request by aditya27marri**
https://engineering.paypalcorp.com/jira/browse/DTALTPAY-5

### CODE REVIEW

**Comment by aditya27marri** [comment]
Retest this please

**Comment by aditya27marri** [comment]
I dont see the failure in my local test run but see it here. Dont know how to fix it

**Comment by aditya27marri** [comment]
Retest this please

**Comment by gregjopa** [comment]
Hi @aditya27marri when you get a chance, can you rebase this with the v4 branch? We fixed the CI build process yesterday for v4.

**Comment by aditya27marri** [comment]
I rebased the code. Please check it and merge it @gregjopa

**Comment by gregjopa** [comment]
Thanks @aditya27marri! Looks great and CI is passing 💯

**Pull request merged**
