### PR TITLE
Get Pay Later AU label from products

### PR DESCRIPTION
**Pull request by elizabethmv**
This PR updates the Pay Later button to check for payIn4 product eligibility to show a Pay in 4 label for AU merchants, otherwise display Pay Later (US/GB).

### CODE REVIEW

**Review by bluepnume — APPROVED** [review]

**Comment by bluepnume** [comment]
Looks good but do we need all the screenshot changes? Or can those be trimmed from the PR?

**Comment by elizabethmv** [comment]
@bluepnume good point, I reverted `products: {
                    payIn4: {
                        eligible: false
                    }
                }` back to `products: {
                    payIn4: {
                        eligible: true
                    }
                }` in the screenshot config. There should only be 3 updated screenshots now :+1:

**Comment by elizabethmv** [comment]
Waiting to merge until GraphQL release is successful.

**Comment by bluepnume** [comment]
Can probably merge this safely now, given there's a good null check. Your call

**Comment by elizabethmv** [comment]
Only reason for waiting is because `payIn4` key currently maps to US until GraphQL changes get out to map `payIn4` to AU instead. Want to make sure we don't show "Pay in 4" for US merchants

**Review by mnicpt — COMMENTED** [review]
LGTM!

**Pull request merged**
