### PR TITLE
Updated style of buttons when on focus to improve a11y

### PR DESCRIPTION
**Pull request by edulopespp**
## Description of the problem:

When navigating with keyboard only, we expect that all items are focusable and able to be seen clearly. However, when navigating with a keyboard with grayscale, some buttons ("PayPal CREDIT" and "Debit or Credit Card") are not able to be visually focusable due to color contrast issues. 
 
## Steps to Reproduce:

Log in to a live paypal account. Once you are at the summary page use this URL: https://www.paypal.com/buttons/smart (will be live in march) to get to the appropriate landing page. After the page loads in turn on grayscale and use your keyboard to navigate the flow of the page. As you are navigating the page tab slowly through the example PayPal buttons and notice that they cannot be seen with grayscale on.

Example:

Screen Shot 2020-05-13 at 3 08 41 PM

## Solution

Updated button's style to have two margins when focused. This is the same style/pattern we are using in other Paypal components to handle focus on grayscale and improve accessibility. With those changes it is clear to se where the focus is when navigating through items with the keyboard.

## Results

# Buttons in pill format (focused)

Screen Shot 2020-05-13 at 1 56 32 PM
Screen Shot 2020-05-13 at 1 59 42 PM

# Buttons in pill format (focused) in grayscale

Screen Shot 2020-05-13 at 1 57 36 PM
Screen Shot 2020-05-13 at 1 59 55 PM

# Buttons in rect format (focused) 

Screen Shot 2020-05-13 at 1 58 21 PM
Screen Shot 2020-05-13 at 1 59 06 PM

# Buttons in rect format (focused) in grayscale

Screen Shot 2020-05-13 at 1 58 42 PM
Screen Shot 2020-05-13 at 1 59 25 PM

### CODE REVIEW

**Comment by bluepnume** [comment]
Thanks!

**Comment by bluepnume** [comment]
Hi -- sorry, I had to revert this. It causes an issue with the vaulted button:

Screen Shot 2020-05-20 at 3 30 31 PM

The click on the caret/dropdown on the right of the button doesn't work, with this extra div in place.

**Comment by lmatab** [comment]
@bluepnume  sorry for posting here but show to create a button for subscription that considers two plans?

**Comment by edulopespp** [comment]
> Hi -- sorry, I had to revert this. It causes an issue with the vaulted button:
> 
> Screen Shot 2020-05-20 at 3 30 31 PM
> 
> The click on the caret/dropdown on the right of the button doesn't work, with this extra div in place.

Hi @bluepnume thank you for letting me know. I will check how we can fix this and submit a PR once I figure that out. Thank you!

**Comment by bluepnume** [comment]
Thanks @edulopespp. Perhaps `pointer-events: none` would work.

**Pull request merged**
