### PR TITLE
adding Q3 payment methods [payu, blik,trustly and verkkopankki]

### PR DESCRIPTION
**Pull request by aditya27marri**
added payu and verkkopankki svgs into paypal sdk logos. whish is used here for new svgs

### CODE REVIEW

**Comment by aditya27marri** [comment]
Checks are failing becasue payu and verkkopankki logos are not in paypal sdk logos yet.

**Comment by aditya27marri** [comment]
Retest this please

**Comment by aditya27marri** [comment]
retest this please

**Comment by amyng** [comment]
Retest this please.

**Pull request merged**
