### PR TITLE
Update README.md 

### PR DESCRIPTION
**Pull request by idivyanshbansal**
###  Added the logo of Paypal to the README.md to make it more interactive to the user and add linking of Paypal to increase 
If this change did not fulfill your needs please comment for any changes or to close this request.  It is really depressing for me to get spam.

the linking of the repository 

### Dependent Changes (if applicable)

❤️  Thank you!

### CODE REVIEW

**Comment by mstuart** [comment]
Hi @idivyanshbansal, is this related to hacktoberfest? Can you link to the issue that you're resolving? Thanks!

**Comment by idivyanshbansal** [comment]
@mstuart sir, Thank you for reviewing my request 😊 . Actually, I find that it will make Readme.md more informative that's why I raise this request, sir. If you find this useful, please accept my request 😟

**Comment by mstuart** [comment]
All good! Appreciate the contribution, but I don't think we need to add a PayPal logo to the README right now. I saw that it links to an image hosted on your repo, but the image link's dead. Okay if I close this? If you're looking for something to contribute, we're participating in Hacktoberfest right now. https://github.com/paypal/hacktoberfest

**Comment by idivyanshbansal** [comment]
@mstuart , No Problem Sir 
Have a great day sir 😊😊

**Pull request closed without merging**
